<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Glyphshift.MonoGame.FontFallback</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
