[package]
name = "glyphshift-adapter-sidefx-cv-paint-buffer-native"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
glyphshift-adapter-native-abi = { path = "../../../platform/native-abi" }
glyphshift-adapter-sidefx-cv-paint-buffer = { path = "../sidefx-cv-paint-buffer" }
retour = { version = "0.3", features = ["thiscall-abi"] }

[dependencies.windows]
version = "0.58"
features = ["Win32_System_LibraryLoader"]

[lints.rust]
unsafe_code = "allow"
